@URL = http://localhost:8080/telefone


### Get All Telephones

GET {{URL}}/telefones HTTP/1.1
Content-Type: application/json

### Get Telephone by id 

GET {{URL}}/telefone/1 HTTP/1.1
Content-Type: application/json

### Create Telephone 

POST {{URL}}/cadastro HTTP/1.1  HTTP/1.1
Content-Type: application/json

{
  "telefone": { "ddd": "11", "numero": "91234-5678" },
  "clienteId": 1
}
### Update Telephone 
PUT {{URL}}/atualizar HTTP/1.1 
Content-Type: application/json

{
  "id": 1,
  "ddd": "79",
  "numero": "faz o L"
}


### Delete telefone 
DELETE {{URL}}/deletar HTTP/1.1
Content-Type: application/json

{
  "id": 1
}
